version: '3'
services:
  mysql:
    image: mysql:5.7
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '10403:3306'
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend

  app:
    build: .
    container_name: node_tsukuteku_api
    environment:
      - DEBUG=app:*
    tty: true
    ports:
      - '10401:3000'
    volumes:
      - ./src:/app
    working_dir: /app
    command: npm run dev
    networks:
      - backend
    depends_on:
      - mysql

networks:
  backend:
